create table "public"."drop later table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."drop later table" enable row level security;

CREATE UNIQUE INDEX "drop later table_pkey" ON public."drop later table" USING btree (id);

alter table "public"."drop later table" add constraint "drop later table_pkey" PRIMARY KEY using index "drop later table_pkey";

grant delete on table "public"."drop later table" to "anon";

grant insert on table "public"."drop later table" to "anon";

grant references on table "public"."drop later table" to "anon";

grant select on table "public"."drop later table" to "anon";

grant trigger on table "public"."drop later table" to "anon";

grant truncate on table "public"."drop later table" to "anon";

grant update on table "public"."drop later table" to "anon";

grant delete on table "public"."drop later table" to "authenticated";

grant insert on table "public"."drop later table" to "authenticated";

grant references on table "public"."drop later table" to "authenticated";

grant select on table "public"."drop later table" to "authenticated";

grant trigger on table "public"."drop later table" to "authenticated";

grant truncate on table "public"."drop later table" to "authenticated";

grant update on table "public"."drop later table" to "authenticated";

grant delete on table "public"."drop later table" to "service_role";

grant insert on table "public"."drop later table" to "service_role";

grant references on table "public"."drop later table" to "service_role";

grant select on table "public"."drop later table" to "service_role";

grant trigger on table "public"."drop later table" to "service_role";

grant truncate on table "public"."drop later table" to "service_role";

grant update on table "public"."drop later table" to "service_role";


